name: Relux
version: 0.5-release
description: Allows manual chunk relighting
author: WhiteWolfdoge (Emily White)
main: net.whiteWolfdoge.relux.ReluxPlugin
database: false
commands:
    relux:
        description: Relights chunks around the player
        usage: /relux

permissions:
    relux.use:
        description: Gives access to Relux command
