name: Relux
version: 1.0-dev
description: Allows manual chunk relighting
author: WhiteWolfdoge (Emily White)
main: net.whiteWolfdoge.relux.ReluxPlugin
database: false
softdepend:
- WorldEdit
commands:
  relux:
    description: Relights chunks around the player
    usage: /relux
permissions:
  relux.use:
    description: Gives access to Relux command